### ISSUE TITLE
🧨 seems to disappear and not reappear, making the game harder 😅

### ISSUE THREAD

**Issue by anaulin** [lahosken/misc#5]
Not sure if this was caused by https://github.com/lahosken/misc/pull/4 or some other change, but the dynamite seems to disappear and not re-appear during a game, making it harder.

https://user-images.githubusercontent.com/6729309/183309861-6133c758-459b-48e0-bdfb-55bc5acb5040.mp4

**Comment by lahosken** [comment]
In theory another firecracker would have appeared evennnnnnnntually, the game was just being really really stingy.

Now it's less stingy. Is it a good level of stingy? I dunno. Relevant code is

`if (Math.random() * (alreadyCount + 0.25) > 0.1) { return }`

...where alreadyCount is how many firecrackers are already on the board. If there are no firecrackers on the grid, this gives you a firecracker 40% of the time. If there's already one firecracker on the grid, this gives about a 1/12 chance of another.

**Comment by anaulin** [comment]
@lahosken yes, it is certainly less stingy and a little less tough now. Thank you!
